### ISSUE TITLE
小白问一下背景怎么换(。﹏。)...

### ISSUE THREAD

**Issue by onexuezha** [AyagawaSeirin/homepage#3]

**Comment by onexuezha** [comment]
`<div id="rin-bg"</div>
<main id="rin-main">`应该是这一串

**Comment by onexuezha** [comment]
貌似是
<div id="rin-bg"</div>
<main id="rin-main">
这一串

**Comment by onexuezha** [comment]
貌似是
`<div id="rin-bg"</div>
<main id="rin-main">`
这串

**Comment by fmkli** [comment]
同问

**Comment by fmkli** [comment]
懂了
1.找到index.html的    《link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/AyagawaSeirin/homepage@latest/assets/css/main.css"》改为    《link rel="stylesheet" href="./assets/css/index.css"》
2.打开assets\css里的main.css
3.找到background-image: url('链接'); 将里面的链接俩字改成你想要的背景的背景链接
防解析html，更换<为《

**Comment by ghost** [comment]
咕噜咕噜咕噜咕噜

**Comment by lboscu** [comment]
一切都是石头门的选择
